/*ToDo action */
//Add
export const TODO_ADD_REQUEST = "ADD NEW TODO";
export const TODO_ADD_SUCCESSED = "ADD NEW TODO SUCCESSED";
export const TODO_ADD_FAILED = "ADD NEW TODO FAILED";
// Edit
export const TODO_EDIT_REQUEST = "EDIT TODO";
export const TODO_EDIT_SUCCESSED = "EDIT TODO SUCCESSED";
export const TODO_EDIT_FAILED = "EDIT TODO FAILED";
//Complete
export const TODO_COMPLETE_REQUEST = "COMPLETE TODO";
export const TODO_COMPLETE_SUCCESSED = "COMPLETE TODO SUCCESSED";
export const TODO_COMPLETE_FAILED = "COMPLETE TODO FAILED";
//DELETE
export const TODO_DELETE_REQUEST = "DELETE TODO";
export const TODO_DELETE_SUCCESSED = "DELETE TODO SUCCESSED";
export const TODO_DELETE_FAILED = "DELETE TODO FAILED";

/*App Action */
export const APP_SET_LOADING_REQUEST = "APP_SET_LOADING_REQUEST";
export const APP_SET_LOADING = "APP_SET_LOADING";
